version: '3.8'
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    ports:
      - '9000:9000'
      - '9092:9092'
    environment:
      - SONARQUBE_JDBC_URL=jdbc:h2:tcp://localhost:9092/sonar
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=admin
      - SONAR_HOST_URL=http://localhost:9000

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
