name: SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    name: SonarQube
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    permissions: read-all
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
